name: vetra_anaam_report
description: "Inventory management system with MongoDB integration and PDF reporting"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Functionality
  mongo_dart: 0.7.6  # Pinned version for stability
  pdf: 3.11.3        # Pinned version
  intl: 0.20.2       # Pinned version

  # File Operations
  path_provider: 2.1.5
  open_file: 3.5.10

  # UI/UX
  syncfusion_flutter_datepicker: 29.1.35
  fluttertoast: 8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1  # Pinned linter version

flutter:
  uses-material-design: true