name: Flutter Android Build -3 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [21, 29, 33]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.2'
          cache: true

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Install Android Tools
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-${{ matrix.api-level }}"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.22.1"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;25.1.8937393"  # Specific NDK version

      - name: Patch FlutterToast build.gradle
        run: |
          sed -i "s/android {/android {\n    namespace 'com.example.fluttertoast'/g" $HOME/.pub-cache/hosted/pub.dev/fluttertoast-*/android/build.gradle

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release --target-platform android-arm64 \
            --build-name=1.0.0 \
            --build-number=${{ github.run_number }} \
            --no-sound-null-safety

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vetra-anaam-android-${{ matrix.api-level }}
          path: build/app/outputs/flutter-apk/app-release.apk
