name: Flutter Android Build -9 

on:
  workflow_dispatch: # Manual trigger only

env:
  FLUTTER_VERSION: "3.29.2"
  TARGET_PLATFORM: "android-arm64"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate AndroidManifest.xml
        run: |
          sudo apt-get install -y libxml2-utils
          if ! xmllint --noout android/app/src/main/AndroidManifest.xml; then
            echo "::error::AndroidManifest.xml has syntax errors"
            exit 1
          fi

      - name: Force V2 Embedding Migration
        run: |
          # Backup original manifest
          cp android/app/src/main/AndroidManifest.xml android/app/src/main/AndroidManifest.xml.bak
          
          # Update AndroidManifest.xml with proper XML structure
          sed -i '1i <?xml version="1.0" encoding="utf-8"?>' android/app/src/main/AndroidManifest.xml
          sed -i '/<application/a \        <meta-data android:name="flutterEmbedding" android:value="2" />' android/app/src/main/AndroidManifest.xml
          
          # Update MainActivity
          find android/app/src/main/kotlin -name 'MainActivity.kt' -exec sed -i 's/extends.*Activity/extends FlutterActivity/' {} \;
          
          # Verify changes
          echo "Updated AndroidManifest.xml:"
          xmllint --format android/app/src/main/AndroidManifest.xml
          echo "Updated MainActivity:"
          find android/app/src/main/kotlin -name 'MainActivity.kt' -exec grep "FlutterActivity" {} \;

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Resolve dependencies
        run: |
          flutter pub cache repair
          flutter pub outdated
          flutter pub upgrade --major-versions
          flutter pub get

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: "34.0.0"
          platform-version: "34"
          ndk-version: "25.2.9519653"

      - name: Build Release APK
        run: |
          flutter build apk --release \
            --target-platform ${{ env.TARGET_PLATFORM }} \
            --dart-define=FLUTTER_BUILD_MODE=release \
            --no-sound-null-safety \
            --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
