name: Flutter Android Build - 7

on:
  workflow_dispatch:  # Manual trigger only

env:
  FLUTTER_VERSION: "3.29.2"
  TARGET_PLATFORM: "android-arm64"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Check and upgrade dependencies
        run: |
          echo "Current dependencies:"
          flutter pub outdated
          echo "Upgrading dependencies..."
          flutter pub upgrade --major-versions
          echo "Updated dependencies:"
          flutter pub outdated

      - name: Verify Flutter Embedding
        run: |
          if grep -q "flutterEmbedding.*1" "android/app/src/main/AndroidManifest.xml"; then
            echo "::error::V1 embedding detected. Update to V2 embedding."
            exit 1
          fi

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: "34.0.0"
          platform-version: "34"

      - name: Build Release APK
        run: |
          flutter build apk --release \
            --target-platform ${{ env.TARGET_PLATFORM }} \
            --dart-define=FLUTTER_BUILD_MODE=release \
            --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
