name: Flutter Android Build - final

on:
  workflow_dispatch: # Manual trigger only

env:
  FLUTTER_VERSION: "3.29.2"
  TARGET_PLATFORM: "android-arm64"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install XML tools
        run: sudo apt-get install -y libxml2-utils

      - name: Validate original AndroidManifest.xml
        run: |
          if ! xmllint --noout android/app/src/main/AndroidManifest.xml; then
            echo "::error::Original AndroidManifest.xml has syntax errors"
            exit 1
          fi
      - name: Update AndroidManifest.xml
        run: |
          cp android/app/src/main/AndroidManifest.xml android/app/src/main/AndroidManifest.xml.bak
          
          # Add meta-data correctly inside <application> if it exists
          if grep -q '<application' android/app/src/main/AndroidManifest.xml; then
            sed -i '/<application/a \        <meta-data android:name="flutterEmbedding" android:value="2" />' android/app/src/main/AndroidManifest.xml
          else
            echo "::error:: <application> tag not found in AndroidManifest.xml"
            exit 1
          fi
          
          # Validate the updated manifest
          if ! xmllint --noout android/app/src/main/AndroidManifest.xml; then
            echo "::error:: Updated AndroidManifest.xml has syntax errors"
            mv android/app/src/main/AndroidManifest.xml.bak android/app/src/main/AndroidManifest.xml
            exit 1
          fi
          
          echo "Updated AndroidManifest.xml:"
          xmllint --format android/app/src/main/AndroidManifest.xml


      - name: Update MainActivity
        run: |
          find android/app/src/main/kotlin -name 'MainActivity.kt' -exec sed -i 's/extends.*Activity/extends FlutterActivity/' {} \;
          echo "Updated MainActivity:"
          find android/app/src/main/kotlin -name 'MainActivity.kt' -exec grep "FlutterActivity" {} \;

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: "34.0.0"
          platform-version: "34"

      - name: Build Release APK
        run: |
          flutter pub get
          flutter build apk --release \
            --target-platform ${{ env.TARGET_PLATFORM }} \
            --dart-define=FLUTTER_BUILD_MODE=release \
            --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
